package com.tcs.Exception;

public class TestException {

	public static void main(String[] args) {
		
		try {
		System.out.println(10/0);
		
		System.out.println("after division");
		}
		catch(ArithmeticException e) {
			e.printStackTrace();
		}
		

	}

}
